services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8081:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local